---
- name: Install python for Ansible
  raw: test -e /usr/bin/python || (apt -y clean python-minimal && apt -y update && apt -y install python-minimal)
  changed_when: False
- setup: # aka gather_facts


 
