---
# tasks file for aws_instance
- name: Launch new instance
  ec2:
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet }}"
    keypair: "{{ keypair }}"
    zone: "{{ zone }}"
    group: "{{ security_groups }}"
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    count: "{{ count }}"
    instance_tags:
      Name: "{{ name }}"
#    volumes: "{{ volumes }}"
    wait: yes
    assign_public_ip: yes
  register: ec2
  
- name: Add new instances to host group
  add_host:
    name: "{{ item.public_dns_name }}"
    #groups: "{{ name }}"
    groupname: launched
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for instance to boot
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 10
    timeout: 30
    state: started
  with_items: "{{ ec2.instances }}"

