- name: Create AzureStack VM Creation
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: myResourceGroup1
      location: local
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: myResourceGroup1
      name: myVnet3
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: myResourceGroup1
      name: mySubnet3
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet3
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: myResourceGroup1
      allocation_method: Static
      name: myPublicIP3
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows RDP
    azure_rm_securitygroup:
      resource_group: myResourceGroup1
      name: myNetworkSecurityGroup3
      rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound
        - name: WINRM
          protocol: Tcp
          destination_port_range: 5986
          access: Allow
          priority: 1002
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: myResourceGroup1
      name: myNIC3
      virtual_network: myVnet3
      subnet: mySubnet3
      public_ip_name: myPublicIP3
      security_group: myNetworkSecurityGroup3
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup1
      name: windows2016
      vm_size: Standard_D1
      managed_disk_type: Standard_LRS
      admin_username: azureuser
      admin_password: Azure123$
      network_interfaces: myNIC3
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
