---
# tasks file for gcp_create_instances
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 20
         source_image: "{{ source_image }}"
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
     
   - name: create a network
     gcp_compute_network:
         name: 'network-instance'
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: network
     
   - name: Create a Firewall
     gcp_compute_firewall:
         name: ansible-firewall
         network: "{{ network }}"#"projects/{{ gcp_project }}/global/networks/{{ network.name }}"
         allowed:
         - ip_protocol: tcp
           ports: ['80','22','443','8080']
         source_ranges: ['0.0.0.0/0']
         project: "{{ gcp_project }}"
         auth_kind: serviceaccount
         service_account_file: "{{ gcp_cred_file }}"
         state: present
     register: firewall
     
   - name: create a address
     gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
    
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: test-vm
         machine_type: "{{ machine_type }}"
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance
     
   - name: Install python for Ansible
     raw: test -e /usr/bin/python || (apt -y clean python-minimal && apt -y update && apt -y install python-minimal)
     changed_when: False
   - setup: # aka gather_facts
   
   - name: Wait for SSH to come up
     wait_for: delay=1 host={{ address.address }} port=22 state=started  timeout=100     
   
   - name: Add host to groupname
     add_host: hostname={{ address.address }} groupname=new_instances
     
   



