---
- name: Create GCP instance
  hosts: localhost
  connection: local
  gather_facts: False
  remote_user: ubuntu
  roles:
    - gcp_create_instances

- name: Manage new instances
  hosts: new_instances
  become: true
  gather_facts: false
  remote_user: ubuntu
  connection: ssh
  roles:
    - python
    - ansible-java8-oracle
    - jenkins
    - tomcat_9
    - tomcat_war_deploy
 
